-- ============================================================
-- FILE: database/run_all.sql
-- Mục đích: Chạy toàn bộ database setup theo đúng thứ tự

-- THỨ TỰ CHẠY:
--   1. schema.sql       → DROP + CREATE tables, indexes
--   2. views.sql        → CREATE views (phụ thuộc bảng)
--   3. triggers.sql     → CREATE triggers (phụ thuộc bảng)
--   4. stored_procs.sql → CREATE stored procedures
--   5. seed_data.sql    → INSERT dữ liệu mẫu
--   [6. test_script_v2.sql → Kiểm thử — chạy riêng sau khi setup xong]
-- ============================================================